yash thakkar


In [ ]:
import numpy as np
import torch

In [ ]:
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')

In [ ]:
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]],dtype='float32')

In [ ]:
 # Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
 # Weights and biases
w = torch.randn(1,3,requires_grad =True)
print(w)
b = torch.randn(1,requires_grad=True)
print(b)

tensor([[ 1.2130, -0.8489,  0.1996]], requires_grad=True)
tensor([2.0445], requires_grad=True)


In [ ]:
# Define the model
def model(x):
  return torch.mm(x,w.t(),out=None) +b

In [ ]:
# Generate predictions
# Compare with targets

preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[42.2990],
        [50.4973],
        [ 5.3962],
        [96.6537],
        [18.2169]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
# MSE loss
# Compute loss
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff = T[k] - P[k]
    square = diff*diff
    sum+=square
  mean = sum/i
  return mean

output = mse(preds,targets)
print("Loss :",output)

Loss : tensor([5357.0615], grad_fn=<DivBackward0>)


In [ ]:
# Compute gradients
print("Gradient :",output.backward())

Gradient : None


In [ ]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 1.2130, -0.8489,  0.1996]], requires_grad=True)
tensor([[-4757.9238, -9501.6748, -4921.1870]])


In [ ]:
# Gradients for bias
print(b)
print(b.grad)

tensor([2.0445], requires_grad=True)
tensor([-67.1748])


In [ ]:
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)

tensor([[ 1.2606, -0.7539,  0.2488]], requires_grad=True)
tensor([2.0451], requires_grad=True)


In [ ]:
# Generate predictions
# Calculate the loss
new_preds = model(inputs)
new_loss = mse(new_preds,targets)
print("New Loss :",new_loss)

New Loss : tensor([4215.6484], grad_fn=<DivBackward0>)


In [ ]:
# Train for 100 epochs
for i in range(200):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor([23.6647], grad_fn=<DivBackward0>)


Pytorch_Built_Ins

In [ ]:
 # Imports
import torch.nn as nn
print(inputs)
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
def model1(x):
  return x @ w.t() +b

In [ ]:
preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[ 57.8160],
        [ 80.9049],
        [120.6081],
        [ 24.6136],
        [ 97.6095]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
loss = nn.MSELoss()
output = loss(preds,targets)
output.backward()
print("Loss :",output)

Loss : tensor(8.3563, grad_fn=<MseLossBackward0>)


In [ ]:
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-0.3063,  0.8971,  0.4649]], requires_grad=True)
tensor([[ 63.3841, -30.5267, -46.1447]])
tensor([0.0779], requires_grad=True)
tensor([0.2208])


In [ ]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [ ]:
preds = model1(inputs)
loss = mse(preds,targets)
 
print(loss)

tensor([2.6967], grad_fn=<DivBackward0>)
