In [ ]:
##1Create Two numpy array of size 4 X 5 and 5 X 4.
import numpy as np
import random as rand

In [ ]:
arra1=np.array(np.arange(0,20).reshape(5,4))
arra2=np.array(np.arange(0,20).reshape(4,5))

In [ ]:
arra1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arra2


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#2.Randomly Initalize that array
array=np.random.randint(1, 100, size=(4, 5))


In [ ]:
array

array([[ 9, 18, 96, 59, 67],
       [53, 95, 71, 22, 88],
       [43, 35, 81, 86, 83],
       [46, 82, 73, 55, 49]])

In [ ]:
#3.Perform matrix multiplication

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(np.dot(x, y))

[[19 22]
 [43 50]]


In [ ]:
print(np.dot(arra1,arra2))

[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]
 [430 484 538 592 646]
 [550 620 690 760 830]]


In [ ]:
#4.4) Perform elementwise matrix multiplication

In [ ]:
print(np.multiply(arra1,arra1))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]
 [256 289 324 361]]


In [ ]:
#5.Find mean, median of the first matrix.

In [ ]:
np.mean(arra1)

9.5

In [ ]:
arra1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
np.mean(arra1,axis=0)

array([ 8.,  9., 10., 11.])

In [ ]:
np.mean(arra1,axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [ ]:
np.median(arra1)

9.5

In [ ]:
np.median(arra1,axis=0)

array([ 8.,  9., 10., 11.])

In [ ]:
np.median(arra1,axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [ ]:
#6.Get the transpose of that Matrix that you created. Create a square matrix and find its deter-
#minant.

In [ ]:
print(arra1.T)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [ ]:
# square matrix 3*3

In [ ]:
array3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.linalg.det(array3)

0.0

In [ ]:
#Obtain each row in the second column of the first array.


In [ ]:
array3[:,1]

array([2, 5, 8])

In [ ]:
#8.Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version


In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data=pd.read_csv('/content/mtcars.csv',usecols=['mpg',	'cyl',	'disp'	,'hp'	,'drat',	'wt'	,'qsec'	,'vs','am','gear','carb'])

In [ ]:
array1=np.array(data)


In [ ]:
array1

array([[ 21.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.62 ,  16.46 ,
          0.   ,   1.   ,   4.   ,   4.   ],
       [ 21.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.875,  17.02 ,
          0.   ,   1.   ,   4.   ,   4.   ],
       [ 22.8  ,   4.   , 108.   ,  93.   ,   3.85 ,   2.32 ,  18.61 ,
          1.   ,   1.   ,   4.   ,   1.   ],
       [ 21.4  ,   6.   , 258.   , 110.   ,   3.08 ,   3.215,  19.44 ,
          1.   ,   0.   ,   3.   ,   1.   ],
       [ 18.7  ,   8.   , 360.   , 175.   ,   3.15 ,   3.44 ,  17.02 ,
          0.   ,   0.   ,   3.   ,   2.   ],
       [ 18.1  ,   6.   , 225.   , 105.   ,   2.76 ,   3.46 ,  20.22 ,
          1.   ,   0.   ,   3.   ,   1.   ],
       [ 14.3  ,   8.   , 360.   , 245.   ,   3.21 ,   3.57 ,  15.84 ,
          0.   ,   0.   ,   3.   ,   4.   ],
       [ 24.4  ,   4.   , 146.7  ,  62.   ,   3.69 ,   3.19 ,  20.   ,
          1.   ,   0.   ,   4.   ,   2.   ],
       [ 22.8  ,   4.   , 140.8  ,  95.   ,   3.92 ,   3.15 ,  22.9  ,
 

In [ ]:
nparrayCentered = array1.T - np.mean(array1, axis=1) # Remove the mean for␣
##,→each row
nparrayCentered = nparrayCentered.T #

In [ ]:
nparrayCentered

array([[-8.90727273e+00, -2.39072727e+01,  1.30092727e+02,
         8.00927273e+01, -2.60072727e+01, -2.72872727e+01,
        -1.34472727e+01, -2.99072727e+01, -2.89072727e+01,
        -2.59072727e+01, -2.59072727e+01],
       [-8.98136364e+00, -2.39813636e+01,  1.30018636e+02,
         8.00186364e+01, -2.60813636e+01, -2.71063636e+01,
        -1.29613636e+01, -2.99813636e+01, -2.89813636e+01,
        -2.59813636e+01, -2.59813636e+01],
       [-7.98181818e-01, -1.95981818e+01,  8.44018182e+01,
         6.94018182e+01, -1.97481818e+01, -2.12781818e+01,
        -4.98818182e+00, -2.25981818e+01, -2.25981818e+01,
        -1.95981818e+01, -2.25981818e+01],
       [-1.73395455e+01, -3.27395455e+01,  2.19260455e+02,
         7.12604545e+01, -3.56595455e+01, -3.55245455e+01,
        -1.92995455e+01, -3.77395455e+01, -3.87395455e+01,
        -3.57395455e+01, -3.77395455e+01],
       [-3.49645455e+01, -4.56645455e+01,  3.06335455e+02,
         1.21335455e+02, -5.05145455e+01, -5.02245455e+01,
  