In [ ]:
import numpy as np
import io
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer.csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

# Declare label as last column in the source file

In [ ]:
#Declaring X as all columns excluding last
X = data.iloc[:,:-1].values

#Declare label as last column in the source file
Y = data.iloc[:,-1].values


In [ ]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X,Y ,
                                   random_state=104, 
                                   test_size=0.25, 
                                   shuffle=True)

In [ ]:
from os import XATTR_SIZE_MAX
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [ ]:
X_train

array([[ 0.39245   ,  0.28266692],
       [-0.25956345, -0.41912681],
       [-1.09786646,  0.48735675],
       [-0.63214256, -1.58878301],
       [-1.09786646, -1.00395491],
       [ 0.11301566,  1.07218485],
       [ 0.85817389,  1.10142626],
       [-1.00472168, -0.33140259],
       [ 0.39245   ,  0.1657013 ],
       [ 0.11301566,  0.10721849],
       [ 0.01987089,  0.04873568],
       [-0.63214256, -1.03319631],
       [ 1.51018735, -1.26712755],
       [-0.07327389,  0.04873568],
       [ 0.85817389,  1.27687469],
       [-1.65673513,  0.37039113],
       [-0.07327389, -0.21443697],
       [-1.37730079, -1.20864474],
       [-0.81843212,  0.39963254],
       [-0.81843212,  0.1657013 ],
       [-0.07327389,  0.31190832],
       [ 0.29930522, -0.18519557],
       [ 0.48559478,  1.24763328],
       [ 1.04446345,  2.09563403],
       [-0.72528734, -1.5303002 ],
       [ 1.78962168, -1.26712755],
       [ 0.39245   ,  1.13066766],
       [ 1.88276646,  2.18335824],
       [ 0.85817389,

In [ ]:
X_test

array([[-1.17093376e+00, -1.21972933e+00],
       [-2.00285827e+00, -8.02931412e-01],
       [-9.62952626e-01,  3.87919774e-01],
       [ 8.04886969e-01, -1.33881445e+00],
       [-1.48290545e+00, -1.47963260e-01],
       [ 3.88924711e-01, -5.64761175e-01],
       [-2.70375467e-02,  6.55861291e-01],
       [ 1.11685866e+00,  1.87648376e+00],
       [-1.89886771e+00, -1.33881445e+00],
       [-2.35018676e-01, -9.81559090e-01],
       [ 1.42883035e+00,  2.23373911e+00],
       [ 1.63681148e+00,  2.14442527e+00],
       [-1.48290545e+00, -6.83846293e-01],
       [ 1.11685866e+00,  1.99556887e+00],
       [ 1.22084923e+00, -9.51787810e-01],
       [ 3.88924711e-01,  3.06644180e-02],
       [ 1.80943582e-01,  1.79520816e-01],
       [ 9.08877533e-01, -1.16018677e+00],
       [ 7.00896404e-01, -9.51787810e-01],
       [-5.46990369e-01,  1.37037200e+00],
       [-2.70375467e-02,  2.68834655e-01],
       [ 8.04886969e-01, -1.45789956e+00],
       [-2.35018676e-01,  5.07004892e-01],
       [-8.

In [ ]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [ ]:
entries = len(X_train[:,0])


In [ ]:
entries

300

In [ ]:
for weights in range(len_x):
  w.append(0)

In [ ]:
w

[0, 0]

In [ ]:
def sigmoid(z):
  return (1/(1+np.exp(-z)))


In [ ]:
def predict(inputs):
  z=np.dot(inputs,w)+b
  h=sigmoid(z)
  for i in range((len(h))):
    if(h[i]>=0.5):
      h[i]=1
    else:
      h[i]=0
  return h
  


In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [ ]:
from scipy.optimize.minpack import shape
def loss_func(y,y1):
  total_loss=np.sum(-y*np.log(y1)-(1-y)*np.log(1-y1))
  m=y.shape[0]
  j=total_loss/m
  return j

In [ ]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
  dw.append(0)

In [ ]:
for i in range(3000):
    z = np.dot(X_train, w) + b
    y_pred = sigmoid(z)
    l = loss_func(y_train, y_pred)
    dw = np.dot((y_pred-y_train).T, X_train)/X_train.shape[0]
    db = np.mean(y_pred-y_train)
    w = w - alpha * dw
    b = b - alpha* db
    print("Round:",i,"Weight:",w,"Bias:",b,"loss:",l)

Round: 0 Weight: [3.01205427 1.77793274] Bias: -1.1913009261098415 loss: 0.3703061695693062
Round: 1 Weight: [3.01131315 1.77399445] Bias: -1.1928845070299532 loss: 0.37011847469935494
Round: 2 Weight: [3.01056544 1.77008445] Bias: -1.1944509216712011 loss: 0.36993347183086495
Round: 3 Weight: [3.00981124 1.76620254] Bias: -1.1960002889803785 loss: 0.36975112147160233
Round: 4 Weight: [3.00905065 1.76234855] Bias: -1.1975327276108105 loss: 0.36957138461746714
Round: 5 Weight: [3.00828376 1.7585223 ] Bias: -1.1990483559133294 loss: 0.36939422274938316
Round: 6 Weight: [3.00751066 1.7547236 ] Bias: -1.2005472919274447 loss: 0.3692195978301193
Round: 7 Weight: [3.00673145 1.75095228] Bias: -1.2020296533727115 loss: 0.3690474723010514
Round: 8 Weight: [3.00594622 1.74720815] Bias: -1.2034955576402928 loss: 0.3688778090788608
Round: 9 Weight: [3.00515506 1.74349104] Bias: -1.2049451217847187 loss: 0.3687105715521766
Round: 10 Weight: [3.00435805 1.73980076] Bias: -1.2063784625158385 loss: 0

In [ ]:
X_train


array([[ 0.39245   ,  0.28266692],
       [-0.25956345, -0.41912681],
       [-1.09786646,  0.48735675],
       [-0.63214256, -1.58878301],
       [-1.09786646, -1.00395491],
       [ 0.11301566,  1.07218485],
       [ 0.85817389,  1.10142626],
       [-1.00472168, -0.33140259],
       [ 0.39245   ,  0.1657013 ],
       [ 0.11301566,  0.10721849],
       [ 0.01987089,  0.04873568],
       [-0.63214256, -1.03319631],
       [ 1.51018735, -1.26712755],
       [-0.07327389,  0.04873568],
       [ 0.85817389,  1.27687469],
       [-1.65673513,  0.37039113],
       [-0.07327389, -0.21443697],
       [-1.37730079, -1.20864474],
       [-0.81843212,  0.39963254],
       [-0.81843212,  0.1657013 ],
       [-0.07327389,  0.31190832],
       [ 0.29930522, -0.18519557],
       [ 0.48559478,  1.24763328],
       [ 1.04446345,  2.09563403],
       [-0.72528734, -1.5303002 ],
       [ 1.78962168, -1.26712755],
       [ 0.39245   ,  1.13066766],
       [ 1.88276646,  2.18335824],
       [ 0.85817389,

In [ ]:
y_pred=predict(X_test)

In [ ]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.])

In [ ]:
#print actual and predicted values in a table
print("actual Value\tpredicted values")
for i in range(len(y_test)):
    print(y_test[i],"\t\t",int(y_pred[i]))

actual Value	predicted values
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
0 		 0
1 		 0
1 		 1
0 		 0
0 		 0
1 		 1
1 		 1
0 		 0
1 		 1
1 		 1
0 		 0
0 		 0
1 		 0
0 		 0
1 		 0
0 		 0
1 		 0
0 		 0
0 		 0
1 		 1
0 		 0
1 		 1
0 		 0
1 		 1
0 		 0
1 		 1
1 		 1
0 		 0
0 		 0
0 		 0
0 		 0
1 		 1
0 		 0
1 		 1
0 		 0
0 		 0
1 		 1
1 		 1
0 		 0
1 		 1
0 		 0
0 		 0
0 		 0
1 		 1
0 		 0
0 		 0
1 		 1
0 		 0
0 		 0
0 		 0
0 		 0
1 		 1
1 		 0
1 		 0
0 		 0
0 		 0
0 		 0
1 		 1
0 		 0
1 		 1
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
1 		 1
0 		 0
0 		 0
0 		 0
0 		 0
1 		 0
0 		 0
0 		 0
0 		 0
0 		 0
1 		 1
0 		 1
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 0
0 		 1
0 		 0
1 		 1
1 		 1
1 		 1
0 		 0
1 		 0
0 		 0


In [ ]:
x=0
for i in range(len(y_test)):
  if(y_test[i]==y_pred[i]):
    x+=1
print((x/len(y_test))*100)


87.0


In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
from sklearn.metrics import  accuracy_score
#Fit
LR.fit(X_train,y_train)

#predicting the test label with LR. Predict always takes X as input
y_test_pred = LR.predict(X_test)
accuracy = accuracy_score(y_test, y_test_pred)*100
print("Accuracy: ", accuracy,"%")

Accuracy:  87.0 %


In [ ]:
y_pred1=predict(X)

In [ ]:
print("actual Value\tpredicted values")
for i in range(len(Y)):
    print(Y[i],"\t\t",int(y_pred1[i]))

actual Value	predicted values
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
1 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
0 		 1
1 		 1
0 		