In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [ ]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [ ]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [ ]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [ ]:
df2=df.sample(frac=1)

In [ ]:
df2.shape

(569, 31)

In [ ]:
hold_on_data=df2.iloc[0:285,:]

In [ ]:
hold_on_data.shape

(285, 31)

In [ ]:
hold_on_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
159        10.90         12.96           68.69      366.8          0.07515   
82         25.22         24.91          171.50     1878.0          0.10630   
307         9.00         14.40           56.36      246.3          0.07005   
443        10.57         18.32           66.82      340.9          0.08142   
530        11.75         17.56           75.89      422.9          0.10730   
..           ...           ...             ...        ...              ...   
83         19.10         26.29          129.10     1132.0          0.12150   
474        10.88         15.62           70.41      358.9          0.10070   
397        12.80         17.46           83.05      508.3          0.08044   
116         8.95         15.76           58.74      245.2          0.09462   
351        15.75         19.22          107.10      758.6          0.12430   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
159           0.03718        0.003090             0.006588         0.1442   
82            0.26650        0.333900             0.184500         0.1829   
307           0.03116        0.003681             0.003472         0.1788   
443           0.04462        0.019930             0.011110         0.2372   
530           0.09713        0.052820             0.044400         0.1598   
..                ...             ...                  ...            ...   
83            0.17910        0.193700             0.146900         0.1634   
474           0.10690        0.051150             0.015710         0.1861   
397           0.08895        0.073900             0.040830         0.1574   
116           0.12430        0.092630             0.023080         0.1305   
351           0.23640        0.291400             0.124200         0.2375   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
159                 0.05743  ...          18.20            78.07       470.0   
82                  0.06782  ...          33.62           211.70      2562.0   
307                 0.06833  ...          20.07            60.90       285.5   
443                 0.05768  ...          23.31            69.35       366.3   
530                 0.06677  ...          27.98            88.52       552.3   
..                      ...  ...            ...              ...         ...   
83                  0.07224  ...          32.72           141.30      1298.0   
474                 0.06837  ...          19.35            80.78       433.1   
397                 0.05750  ...          21.06            90.72       591.0   
116                 0.07163  ...          17.07            63.34       270.0   
351                 0.07603  ...          24.17           119.40       915.3   

     worst smoothness  worst compactness  worst concavity  \
159           0.11710            0.08294          0.01854   
82            0.15730            0.60760          0.64760   
307           0.09861            0.05232          0.01472   
443           0.09794            0.06542          0.03986   
530           0.13490            0.18540          0.13660   
..                ...                ...              ...   
83            0.13920            0.28170          0.24320   
474           0.13320            0.38980          0.33650   
397           0.09534            0.18120          0.19010   
116           0.11790            0.18790          0.15440   
351           0.15500            0.50460          0.68720   

     worst concave points  worst symmetry  worst fractal dimension  target  
159               0.03953          0.2738                  0.07685       1  
82                0.28670          0.2355                  0.10510       0  
307               0.01389          0.2991                  0.07804       1  
443               0.02222          0.2699                  0.06736       1  
530               0.10100          0.2478                  0.077

In [ ]:
df1=df2.iloc[286:569,:]

In [ ]:
y=df1.iloc[:,-1]

In [ ]:
y

293    1
329    0
60     1
19     1
228    1
      ..
354    1
420    1
349    1
115    1
130    1
Name: target, Length: 283, dtype: int64

In [ ]:
X=df1.iloc[:,:-1]

In [ ]:
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
293        11.85         17.46           75.54      432.7          0.08372   
329        16.26         21.88          107.50      826.8          0.11650   
60         10.17         14.88           64.55      311.9          0.11340   
19         13.54         14.36           87.46      566.3          0.09779   
228        12.62         23.97           81.35      496.4          0.07903   
..           ...           ...             ...        ...              ...   
354        11.14         14.07           71.24      384.6          0.07274   
420        11.57         19.04           74.20      409.7          0.08546   
349        11.95         14.96           77.23      426.7          0.11580   
115        11.93         21.53           76.53      438.6          0.09768   
130        12.19         13.29           79.08      455.8          0.10660   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
293           0.05642         0.02688              0.02280         0.1875   
329           0.12830         0.17990              0.07981         0.1869   
60            0.08061         0.01084              0.01290         0.2743   
19            0.08129         0.06664              0.04781         0.1885   
228           0.07529         0.05438              0.02036         0.1514   
..                ...             ...                  ...            ...   
354           0.06064         0.04505              0.01471         0.1690   
420           0.07722         0.05485              0.01428         0.2031   
349           0.12060         0.01171              0.01787         0.2459   
115           0.07849         0.03328              0.02008         0.1688   
130           0.09509         0.02855              0.02882         0.1880   

     mean fractal dimension  ...  worst radius  worst texture  \
293                 0.05715  ...         13.06          25.75   
329                 0.06532  ...         17.73          25.21   
60                  0.06960  ...         11.02          17.45   
19                  0.05766  ...         15.11          19.26   
228                 0.06019  ...         14.20          31.31   
..                      ...  ...           ...            ...   
354                 0.06083  ...         12.12          15.82   
420                 0.06267  ...         13.07          26.98   
349                 0.06581  ...         12.81          17.72   
115                 0.06194  ...         13.67          26.15   
130                 0.06471  ...         13.34          17.81   

     worst perimeter  worst area  worst smoothness  worst compactness  \
293            84.35       517.8           0.13690            0.17580   
329           113.70       975.2           0.14260            0.21160   
60             69.86       368.6           0.12750            0.09866   
19             99.70       711.2           0.14400            0.17730   
228            90.67       624.0           0.12270            0.34540   
..               ...         ...               ...                ...   
354            79.62       453.5           0.08864            0.12560   
420            86.43       520.5           0.12490            0.19370   
349            83.09       496.2           0.12930            0.18850   
115            87.54       583.0           0.15000            0.23990   
130            91.38       545.2           0.14270            0.25850   

     worst concavity  worst concave points  worst symmetry  \
293          0.13160               0.09140          0.3101   
329          0.33440               0.10470          0.2736   
60           0.02168               0.02579          0.3557   
19           0.23900               0.12880          0.2977   
228          0.39110               0.11800          0.2826   
..               ...                   ...             ...   
354          0.12010               0.03922         

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [ ]:
X

array([[-0.59476305, -0.39684659, -0.62537643, ..., -0.30595238,
         0.32358962, -0.81808786],
       [ 0.64056408,  0.63403317,  0.67907049, ..., -0.09652043,
        -0.26818471, -0.24170044],
       [-1.06536386, -0.99858184, -1.07393311, ..., -1.33909754,
         1.0629022 , -0.20087807],
       ...,
       [-0.5667511 , -0.97992338, -0.5563991 , ..., -0.99471582,
         0.36087951, -0.46287235],
       [-0.57235349,  0.55240242, -0.58496959, ..., -0.60403862,
        -0.75133197,  0.11656151],
       [-0.49952241, -1.36941868, -0.48089138, ..., -0.45601904,
         0.92022784,  0.54306383]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [ ]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [ ]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [ ]:
h_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
159        10.90         12.96           68.69      366.8          0.07515   
82         25.22         24.91          171.50     1878.0          0.10630   
307         9.00         14.40           56.36      246.3          0.07005   
443        10.57         18.32           66.82      340.9          0.08142   
530        11.75         17.56           75.89      422.9          0.10730   
..           ...           ...             ...        ...              ...   
83         19.10         26.29          129.10     1132.0          0.12150   
474        10.88         15.62           70.41      358.9          0.10070   
397        12.80         17.46           83.05      508.3          0.08044   
116         8.95         15.76           58.74      245.2          0.09462   
351        15.75         19.22          107.10      758.6          0.12430   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
159           0.03718        0.003090             0.006588         0.1442   
82            0.26650        0.333900             0.184500         0.1829   
307           0.03116        0.003681             0.003472         0.1788   
443           0.04462        0.019930             0.011110         0.2372   
530           0.09713        0.052820             0.044400         0.1598   
..                ...             ...                  ...            ...   
83            0.17910        0.193700             0.146900         0.1634   
474           0.10690        0.051150             0.015710         0.1861   
397           0.08895        0.073900             0.040830         0.1574   
116           0.12430        0.092630             0.023080         0.1305   
351           0.23640        0.291400             0.124200         0.2375   

     mean fractal dimension  ...  worst radius  worst texture  \
159                 0.05743  ...        12.360          18.20   
82                  0.06782  ...        30.000          33.62   
307                 0.06833  ...         9.699          20.07   
443                 0.05768  ...        10.940          23.31   
530                 0.06677  ...        13.500          27.98   
..                      ...  ...           ...            ...   
83                  0.07224  ...        20.330          32.72   
474                 0.06837  ...        11.940          19.35   
397                 0.05750  ...        13.740          21.06   
116                 0.07163  ...         9.414          17.07   
351                 0.07603  ...        17.360          24.17   

     worst perimeter  worst area  worst smoothness  worst compactness  \
159            78.07       470.0           0.11710            0.08294   
82            211.70      2562.0           0.15730            0.60760   
307            60.90       285.5           0.09861            0.05232   
443            69.35       366.3           0.09794            0.06542   
530            88.52       552.3           0.13490            0.18540   
..               ...         ...               ...                ...   
83            141.30      1298.0           0.13920            0.28170   
474            80.78       433.1           0.13320            0.38980   
397            90.72       591.0           0.09534            0.18120   
116            63.34       270.0           0.11790            0.18790   
351           119.40       915.3           0.15500            0.50460   

     worst concavity  worst concave points  worst symmetry  \
159          0.01854               0.03953          0.2738   
82           0.64760               0.28670          0.2355   
307          0.01472               0.01389          0.2991   
443          0.03986               0.02222          0.2699   
530          0.13660               0.10100          0.2478   
..               ...                   ...             ...   
83           0.24320               0.18410         

In [ ]:
h_X=sc.fit_transform(h_X)

In [ ]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [ ]:
x1

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0])

In [ ]:
x2

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0])

In [ ]:
x3

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0])

In [ ]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [ ]:
df4=df3.T

In [ ]:
df4

0  1  2
0    1  1  1
1    0  0  0
2    1  1  1
3    1  1  1
4    1  1  1
..  .. .. ..
280  0  0  0
281  1  1  1
282  1  1  1
283  1  1  1
284  0  0  0

[285 rows x 3 columns]

In [ ]:
lr2=LogisticRegression()

In [ ]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [ ]:
df4_X

0  1  2
0    1  1  1
1    0  0  0
2    1  1  1
3    1  1  1
4    1  1  1
..  .. .. ..
280  0  0  0
281  1  1  1
282  1  1  1
283  1  1  1
284  0  0  0

[285 rows x 3 columns]

In [ ]:
df4_Y

159    1
82     0
307    1
443    1
530    1
      ..
83     0
474    1
397    1
116    1
351    0
Name: target, Length: 285, dtype: int64

In [ ]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [ ]:
X_test=sc.fit_transform(X_test)

In [ ]:
X_test

array([[-0.26117561, -1.17775571, -0.28101901, ...,  0.09817999,
         0.09278723, -0.70652763],
       [-0.08443767,  0.2693446 , -0.08880676, ...,  0.17596849,
        -0.61747857, -0.36926558],
       [-0.35222244, -0.83533003, -0.41265527, ..., -1.48504475,
        -0.42989144, -0.07254255],
       ...,
       [-0.24243068,  1.31303931, -0.25810886, ..., -0.06044754,
        -0.42989144, -0.62882786],
       [-0.70837618,  0.50622811, -0.69378994, ..., -0.53175432,
        -0.98463629,  0.80974398],
       [ 1.5865393 ,  0.56251727,  1.51839822, ...,  0.82573124,
        -0.49723041, -1.00156154]])

In [ ]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [ ]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [ ]:
df6=df5.T

In [ ]:
df6

0  1  2
0   1  1  1
1   1  1  1
2   1  1  1
3   0  0  0
4   1  1  1
.. .. .. ..
89  1  1  1
90  1  1  1
91  1  1  1
92  1  1  1
93  0  0  0

[94 rows x 3 columns]

In [ ]:
df6_X=df6.iloc[:,:]


In [ ]:
final=lr2.predict(df6_X)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test, final)

0.9361702127659575

In [137]:
from sklearn.ensemble import StackingClassifier

In [138]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [139]:
df_X=sc.fit_transform(df_X)

In [141]:
df_X.shape

(569, 30)

In [142]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [143]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [144]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [146]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [147]:
final1=clf.predict(df_X_test)

In [148]:
accuracy_score(df_y_test, final1)

0.9680851063829787